package com.luntan.demo.mappers;

import com.luntan.demo.model.Users;
import com.luntan.demo.model.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    List<Users> selectByExampleWithRowbounds(UsersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_s
     *
     * @mbg.generated Thu Dec 12 20:31:13 CST 2019
     */
    int updateByPrimaryKey(Users record);
}